env:
# ENCRYPTED
  CLONE: "ENCRYPTED[8069b89d910d6582970f63985eb6d6606f2b9d56e1b6c638b3695f66b188562730c73703052136fec902d3dadaecd83c]"

# FLAG
  WORKDIR: "/usr/src/app"
  CIRRUS_CLONE_DEPTH: "1"

task:
  name: "Setting Up, Syncing, Building and Uploading"
  only_if: $CIRRUS_REPO_OWNER == 'Deaimded'
  timeout_in: 100m
  container:
    image: gengkapak/app:latest
    cpu: 4
    memory: 16G
  RUN: ./start.sh
